# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifications/battery_update.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.battery_pb2 as battery__pb2

from proto.battery_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"notifications/battery_update.proto\x12\x11insta360.messages\x1a\rbattery.proto\"S\n\x19NotificationBatteryUpdate\x12\x36\n\x0e\x62\x61ttery_status\x18\x01 \x01(\x0b\x32\x1e.insta360.messages.BatteryInfoB\x08\xa2\x02\x05INSPBP\x00\x62\x06proto3')



_NOTIFICATIONBATTERYUPDATE = DESCRIPTOR.message_types_by_name['NotificationBatteryUpdate']
NotificationBatteryUpdate = _reflection.GeneratedProtocolMessageType('NotificationBatteryUpdate', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONBATTERYUPDATE,
  '__module__' : 'notifications.battery_update_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.NotificationBatteryUpdate)
  })
_sym_db.RegisterMessage(NotificationBatteryUpdate)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\242\002\005INSPB'
  _NOTIFICATIONBATTERYUPDATE._serialized_start=72
  _NOTIFICATIONBATTERYUPDATE._serialized_end=155
# @@protoc_insertion_point(module_scope)
