CIPHER_CIPHERTEXT_KEY = 'CIPHERTEXT'
CIPHER_PRIVATE_KEY_KEY = 'PRIVATE_KEY'

FUNCTION_SELF_KEY = 'self'
FUNCTION_RPC_KEY = 'RpcFunction'
FUNCTION_WORK_KEY = 'WorkFunction'

FUNCTION_PARAM_NAME_KEY = 'param_name'
FUNCTION_PARAM_DEFAULT_VALUE_KEY = 'default_value'

PROXY_RPC_KEY = 'rpc'
PROXY_NAME_KEY = 'pyzrpc'
PROXY_METHOD_NAME_KEY = 'call'

NAME_KEY = 'name'
SERVICE_PID_KEY = 'service_pid'
SERVICE_NAME_KEY = 'service_name'
SERVICE_IPADDR_KEY = 'service_ipaddr'
SERVICE_VERSION_KEY = 'service_version'
SERVICE_FUNCTIONS_KEY = 'service_functions'

WORK_PID_KEY = 'work_pid'
WORK_NAME_KEY = 'work_name'
WORK_IPADDR_KEY = 'work_ipaddr'
WORK_VERSION_KEY = 'work_version'
WORK_FUNCTIONS_KEY = 'work_functions'
WORK_MAX_PROCESS_KEY = 'work_max_process'
WORK_RUN_PROCESS_KEY = 'work_run_process'

TASK_ID_KEY = 'task_id'
TASK_BODY_KEY = 'body'

TASK_END_TIME_KEY = 'end_time'
TASK_CREATE_TIME_KEY = 'create_time'

CONFIG_MONGO_KEY = 'MONGODB_CONFIG'
CONFIG_RABBIT_KEY = 'RABBITMQ_CONFIG'
CONFIG_ROOT_PATH_KEY = 'ROOT_PATH'
CONFIG_AMQP_URI_KEY = 'AMQP_URI'

MONGO_DBNAME_KEY = 'PYZRPC'

SOCKET_BIND_IP = '8.8.8.8'
SOCKET_BIND_PORT = 80
SOCKET_SHUTDOWN_SLEEP = 2

CONFIG_DEFAULT_TIMEZONE = 'Asia/Shanghai'
CONFIG_DEFAULT_FORMAT = '%Y%m%d%H%M%S'

NODE_IPADDR_KEY = 'ipaddr'

FLASK_STATUS_DEFAULT_VALUE_KEY = False
FLASK_HOST_DEFAULT_VALUE_KEY = '0.0.0.0'
FLASK_PORT_DEFAULT_VALUE_KEY = 8501
FLASK_USERNAME_DEFAULT_VALUE_KEY = 'admin'
FLASK_PASSWORD_DEFAULT_VALUE_KEY = 'admin'

FLASK_STATUS_KEY = 'IS_ADMIN'
FLASK_HOST_KEY = 'FLASK_HOST'
FLASK_PORT_KEY = 'FLASK_PORT'
FLASK_USERNAME_KEY = 'FLASK_USERNAME'
FLASK_PASSWORD_KEY = 'FLASK_PASSWORD'
FLASK_WEB_KEY = 'http'
