# Generated by Django 5.1.3 on 2024-11-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
