# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands/open_camera_oled.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63ommands/open_camera_oled.proto\x12\x11insta360.messages\"\x10\n\x0eOpenCameraOled\"\x14\n\x12OpenCameraOledRespB\x08\xa2\x02\x05INSPBb\x06proto3')



_OPENCAMERAOLED = DESCRIPTOR.message_types_by_name['OpenCameraOled']
_OPENCAMERAOLEDRESP = DESCRIPTOR.message_types_by_name['OpenCameraOledResp']
OpenCameraOled = _reflection.GeneratedProtocolMessageType('OpenCameraOled', (_message.Message,), {
  'DESCRIPTOR' : _OPENCAMERAOLED,
  '__module__' : 'commands.open_camera_oled_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.OpenCameraOled)
  })
_sym_db.RegisterMessage(OpenCameraOled)

OpenCameraOledResp = _reflection.GeneratedProtocolMessageType('OpenCameraOledResp', (_message.Message,), {
  'DESCRIPTOR' : _OPENCAMERAOLEDRESP,
  '__module__' : 'commands.open_camera_oled_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.OpenCameraOledResp)
  })
_sym_db.RegisterMessage(OpenCameraOledResp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\242\002\005INSPB'
  _OPENCAMERAOLED._serialized_start=54
  _OPENCAMERAOLED._serialized_end=70
  _OPENCAMERAOLEDRESP._serialized_start=72
  _OPENCAMERAOLEDRESP._serialized_end=92
# @@protoc_insertion_point(module_scope)
