# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pylivoltek
from pylivoltek.models.energy_store_battery_type import EnergyStoreBatteryType  # noqa: E501
from pylivoltek.rest import ApiException


class TestEnergyStoreBatteryType(unittest.TestCase):
    """EnergyStoreBatteryType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnergyStoreBatteryType(self):
        """Test EnergyStoreBatteryType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pylivoltek.models.energy_store_battery_type.EnergyStoreBatteryType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
