# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands/sta_wifi_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.options_pb2 as options__pb2
try:
  photo__pb2 = options__pb2.photo__pb2
except AttributeError:
  photo__pb2 = options__pb2.photo_pb2
try:
  video__pb2 = options__pb2.video__pb2
except AttributeError:
  video__pb2 = options__pb2.video_pb2
try:
  battery__pb2 = options__pb2.battery__pb2
except AttributeError:
  battery__pb2 = options__pb2.battery_pb2
try:
  storage__pb2 = options__pb2.storage__pb2
except AttributeError:
  storage__pb2 = options__pb2.storage_pb2
try:
  button__press__pb2 = options__pb2.button__press__pb2
except AttributeError:
  button__press__pb2 = options__pb2.button_press_pb2
try:
  flicker__pb2 = options__pb2.flicker__pb2
except AttributeError:
  flicker__pb2 = options__pb2.flicker_pb2
try:
  sensor__pb2 = options__pb2.sensor__pb2
except AttributeError:
  sensor__pb2 = options__pb2.sensor_pb2
try:
  bluetooth__pb2 = options__pb2.bluetooth__pb2
except AttributeError:
  bluetooth__pb2 = options__pb2.bluetooth_pb2
try:
  chargebox__pb2 = options__pb2.chargebox__pb2
except AttributeError:
  chargebox__pb2 = options__pb2.chargebox_pb2
try:
  battery__pb2 = options__pb2.battery__pb2
except AttributeError:
  battery__pb2 = options__pb2.battery_pb2
try:
  ptz__pb2 = options__pb2.ptz__pb2
except AttributeError:
  ptz__pb2 = options__pb2.ptz_pb2

from proto.options_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63ommands/sta_wifi_info.proto\x12\x11insta360.messages\x1a\roptions.proto\"I\n\x0bStaWifiInfo\x12:\n\rsta_wifi_info\x18\x01 \x01(\x0b\x32#.insta360.messages.Options.WifiInfo\"\x11\n\x0fStaWifiInfoRespB\x08\xa2\x02\x05INSPBP\x00\x62\x06proto3')



_STAWIFIINFO = DESCRIPTOR.message_types_by_name['StaWifiInfo']
_STAWIFIINFORESP = DESCRIPTOR.message_types_by_name['StaWifiInfoResp']
StaWifiInfo = _reflection.GeneratedProtocolMessageType('StaWifiInfo', (_message.Message,), {
  'DESCRIPTOR' : _STAWIFIINFO,
  '__module__' : 'commands.sta_wifi_info_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.StaWifiInfo)
  })
_sym_db.RegisterMessage(StaWifiInfo)

StaWifiInfoResp = _reflection.GeneratedProtocolMessageType('StaWifiInfoResp', (_message.Message,), {
  'DESCRIPTOR' : _STAWIFIINFORESP,
  '__module__' : 'commands.sta_wifi_info_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.StaWifiInfoResp)
  })
_sym_db.RegisterMessage(StaWifiInfoResp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\242\002\005INSPB'
  _STAWIFIINFO._serialized_start=66
  _STAWIFIINFO._serialized_end=139
  _STAWIFIINFORESP._serialized_start=141
  _STAWIFIINFORESP._serialized_end=158
# @@protoc_insertion_point(module_scope)
