# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifications/shutdown.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cnotifications/shutdown.proto\x12\x11insta360.messages\"\xaa\x01\n\x14NotificationShutdown\x12\x45\n\nerror_code\x18\x01 \x01(\x0e\x32\x31.insta360.messages.NotificationShutdown.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\tErrorCode\x12\x12\n\x0e\x42\x41TTERT_RUNOUT\x10\x00\x12\x19\n\x15TEMPERATURE_OVERLIMIT\x10\x01\x42\x08\xa2\x02\x05INSPBb\x06proto3')



_NOTIFICATIONSHUTDOWN = DESCRIPTOR.message_types_by_name['NotificationShutdown']
_NOTIFICATIONSHUTDOWN_ERRORCODE = _NOTIFICATIONSHUTDOWN.enum_types_by_name['ErrorCode']
NotificationShutdown = _reflection.GeneratedProtocolMessageType('NotificationShutdown', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONSHUTDOWN,
  '__module__' : 'notifications.shutdown_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.NotificationShutdown)
  })
_sym_db.RegisterMessage(NotificationShutdown)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\242\002\005INSPB'
  _NOTIFICATIONSHUTDOWN._serialized_start=52
  _NOTIFICATIONSHUTDOWN._serialized_end=222
  _NOTIFICATIONSHUTDOWN_ERRORCODE._serialized_start=164
  _NOTIFICATIONSHUTDOWN_ERRORCODE._serialized_end=222
# @@protoc_insertion_point(module_scope)
