# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands/get_sync_capture_mode.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.sync_capture_mode_pb2 as sync__capture__mode__pb2

from proto.sync_capture_mode_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$commands/get_sync_capture_mode.proto\x12\x11insta360.messages\x1a\x17sync_capture_mode.proto\"\x14\n\x12GetSyncCaptureMode\"R\n\x16GetSyncCaptureModeResp\x12\x38\n\x0c\x63\x61pture_mode\x18\x01 \x01(\x0e\x32\".insta360.messages.SyncCaptureModeB\x08\xa2\x02\x05INSPBP\x00\x62\x06proto3')



_GETSYNCCAPTUREMODE = DESCRIPTOR.message_types_by_name['GetSyncCaptureMode']
_GETSYNCCAPTUREMODERESP = DESCRIPTOR.message_types_by_name['GetSyncCaptureModeResp']
GetSyncCaptureMode = _reflection.GeneratedProtocolMessageType('GetSyncCaptureMode', (_message.Message,), {
  'DESCRIPTOR' : _GETSYNCCAPTUREMODE,
  '__module__' : 'commands.get_sync_capture_mode_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetSyncCaptureMode)
  })
_sym_db.RegisterMessage(GetSyncCaptureMode)

GetSyncCaptureModeResp = _reflection.GeneratedProtocolMessageType('GetSyncCaptureModeResp', (_message.Message,), {
  'DESCRIPTOR' : _GETSYNCCAPTUREMODERESP,
  '__module__' : 'commands.get_sync_capture_mode_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetSyncCaptureModeResp)
  })
_sym_db.RegisterMessage(GetSyncCaptureModeResp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\242\002\005INSPB'
  _GETSYNCCAPTUREMODE._serialized_start=84
  _GETSYNCCAPTUREMODE._serialized_end=104
  _GETSYNCCAPTUREMODERESP._serialized_start=106
  _GETSYNCCAPTUREMODERESP._serialized_end=188
# @@protoc_insertion_point(module_scope)
