# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands/get_multi_photography_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.options_pb2 as options__pb2
try:
  photo__pb2 = options__pb2.photo__pb2
except AttributeError:
  photo__pb2 = options__pb2.photo_pb2
try:
  video__pb2 = options__pb2.video__pb2
except AttributeError:
  video__pb2 = options__pb2.video_pb2
try:
  battery__pb2 = options__pb2.battery__pb2
except AttributeError:
  battery__pb2 = options__pb2.battery_pb2
try:
  storage__pb2 = options__pb2.storage__pb2
except AttributeError:
  storage__pb2 = options__pb2.storage_pb2
try:
  button__press__pb2 = options__pb2.button__press__pb2
except AttributeError:
  button__press__pb2 = options__pb2.button_press_pb2
try:
  flicker__pb2 = options__pb2.flicker__pb2
except AttributeError:
  flicker__pb2 = options__pb2.flicker_pb2
try:
  sensor__pb2 = options__pb2.sensor__pb2
except AttributeError:
  sensor__pb2 = options__pb2.sensor_pb2
try:
  bluetooth__pb2 = options__pb2.bluetooth__pb2
except AttributeError:
  bluetooth__pb2 = options__pb2.bluetooth_pb2
try:
  chargebox__pb2 = options__pb2.chargebox__pb2
except AttributeError:
  chargebox__pb2 = options__pb2.chargebox_pb2
try:
  battery__pb2 = options__pb2.battery__pb2
except AttributeError:
  battery__pb2 = options__pb2.battery_pb2
try:
  ptz__pb2 = options__pb2.ptz__pb2
except AttributeError:
  ptz__pb2 = options__pb2.ptz_pb2
import proto.multi_photography_options_pb2 as multi__photography__options__pb2
try:
  video__pb2 = multi__photography__options__pb2.video__pb2
except AttributeError:
  video__pb2 = multi__photography__options__pb2.video_pb2
try:
  sensor__pb2 = multi__photography__options__pb2.sensor__pb2
except AttributeError:
  sensor__pb2 = multi__photography__options__pb2.sensor_pb2

from proto.options_pb2 import *
from proto.multi_photography_options_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,commands/get_multi_photography_options.proto\x12\x11insta360.messages\x1a\roptions.proto\x1a\x1fmulti_photography_options.proto\"\xcb\x01\n\x1aGetMultiPhotographyOptions\x12\x44\n\x0coption_types\x18\x01 \x03(\x0e\x32..insta360.messages.MultiPhotographyOptionsType\x12/\n\x06\x64\x65vice\x18\x02 \x01(\x0e\x32\x1f.insta360.messages.SensorDevice\x12\x36\n\rfunction_mode\x18\x03 \x01(\x0e\x32\x1f.insta360.messages.FunctionMode\"\xa1\x01\n\x1eGetMultiPhotographyOptionsResp\x12\x44\n\x0coption_types\x18\x01 \x03(\x0e\x32..insta360.messages.MultiPhotographyOptionsType\x12\x39\n\x05value\x18\x02 \x01(\x0b\x32*.insta360.messages.MultiPhotographyOptionsB\x08\xa2\x02\x05INSPBP\x00P\x01\x62\x06proto3')



_GETMULTIPHOTOGRAPHYOPTIONS = DESCRIPTOR.message_types_by_name['GetMultiPhotographyOptions']
_GETMULTIPHOTOGRAPHYOPTIONSRESP = DESCRIPTOR.message_types_by_name['GetMultiPhotographyOptionsResp']
GetMultiPhotographyOptions = _reflection.GeneratedProtocolMessageType('GetMultiPhotographyOptions', (_message.Message,), {
  'DESCRIPTOR' : _GETMULTIPHOTOGRAPHYOPTIONS,
  '__module__' : 'commands.get_multi_photography_options_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetMultiPhotographyOptions)
  })
_sym_db.RegisterMessage(GetMultiPhotographyOptions)

GetMultiPhotographyOptionsResp = _reflection.GeneratedProtocolMessageType('GetMultiPhotographyOptionsResp', (_message.Message,), {
  'DESCRIPTOR' : _GETMULTIPHOTOGRAPHYOPTIONSRESP,
  '__module__' : 'commands.get_multi_photography_options_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetMultiPhotographyOptionsResp)
  })
_sym_db.RegisterMessage(GetMultiPhotographyOptionsResp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\242\002\005INSPB'
  _GETMULTIPHOTOGRAPHYOPTIONS._serialized_start=116
  _GETMULTIPHOTOGRAPHYOPTIONS._serialized_end=319
  _GETMULTIPHOTOGRAPHYOPTIONSRESP._serialized_start=322
  _GETMULTIPHOTOGRAPHYOPTIONSRESP._serialized_end=483
# @@protoc_insertion_point(module_scope)
