# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands/get_timelapse_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.timelapse_pb2 as timelapse__pb2

from proto.timelapse_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$commands/get_timelapse_options.proto\x12\x11insta360.messages\x1a\x0ftimelapse.proto\"E\n\x13GetTimelapseOptions\x12.\n\x04mode\x18\x01 \x01(\x0e\x32 .insta360.messages.TimelapseMode\"Y\n\x17GetTimelapseOptionsResp\x12>\n\x11timelapse_options\x18\x01 \x01(\x0b\x32#.insta360.messages.TimelapseOptionsB\x08\xa2\x02\x05INSPBP\x00\x62\x06proto3')



_GETTIMELAPSEOPTIONS = DESCRIPTOR.message_types_by_name['GetTimelapseOptions']
_GETTIMELAPSEOPTIONSRESP = DESCRIPTOR.message_types_by_name['GetTimelapseOptionsResp']
GetTimelapseOptions = _reflection.GeneratedProtocolMessageType('GetTimelapseOptions', (_message.Message,), {
  'DESCRIPTOR' : _GETTIMELAPSEOPTIONS,
  '__module__' : 'commands.get_timelapse_options_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetTimelapseOptions)
  })
_sym_db.RegisterMessage(GetTimelapseOptions)

GetTimelapseOptionsResp = _reflection.GeneratedProtocolMessageType('GetTimelapseOptionsResp', (_message.Message,), {
  'DESCRIPTOR' : _GETTIMELAPSEOPTIONSRESP,
  '__module__' : 'commands.get_timelapse_options_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetTimelapseOptionsResp)
  })
_sym_db.RegisterMessage(GetTimelapseOptionsResp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\242\002\005INSPB'
  _GETTIMELAPSEOPTIONS._serialized_start=76
  _GETTIMELAPSEOPTIONS._serialized_end=145
  _GETTIMELAPSEOPTIONSRESP._serialized_start=147
  _GETTIMELAPSEOPTIONSRESP._serialized_end=236
# @@protoc_insertion_point(module_scope)
