from Illuminate.Collections.Collection import Collection as Collection
from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest
from djing.core.Tool import Tool

class ResourceManager(Tool):
    def menu(self, request: DjingRequest): ...
    def grouped_menu(self, grouped_resources, request: DjingRequest): ...
    def ungrouped_menu(self, grouped_resources: Collection, request: DjingRequest): ...
