from .CONTCAR_AND_POSCAR_CONFIG import *

__all__ = [
    "NAME_LINE",
    "SCALING_FACTOR_LINE",
    "LATTICE_VECTORS_START_LINE",
    "LATTICE_VECTORS_END_LINE",
    "ATOM_TYPE_LINE",
    "ATOM_NUMBER_LINE"
]