# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands/bt_central.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.bluetooth_pb2 as bluetooth__pb2

from proto.bluetooth_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63ommands/bt_central.proto\x12\x11insta360.messages\x1a\x0f\x62luetooth.proto\"P\n\x10ScanBTPeripheral\x12<\n\x0fperipheral_type\x18\x01 \x01(\x0e\x32#.insta360.messages.BTPeripheralType\"L\n\x15\x43onnectToBTPeripheral\x12\x33\n\nperipheral\x18\x01 \x01(\x0b\x32\x1f.insta360.messages.BTPeripheral\"M\n\x16\x44isconnectBTPeripheral\x12\x33\n\nperipheral\x18\x01 \x01(\x0b\x32\x1f.insta360.messages.BTPeripheral\"X\n\x18GetConnectedBTPeripheral\x12<\n\x0fperipheral_type\x18\x01 \x01(\x0e\x32#.insta360.messages.BTPeripheralType\"T\n\x1cGetConnectedBTPeripheralResp\x12\x34\n\x0bperipherals\x18\x01 \x03(\x0b\x32\x1f.insta360.messages.BTPeripheralB\x08\xa2\x02\x05INSPBP\x00\x62\x06proto3')



_SCANBTPERIPHERAL = DESCRIPTOR.message_types_by_name['ScanBTPeripheral']
_CONNECTTOBTPERIPHERAL = DESCRIPTOR.message_types_by_name['ConnectToBTPeripheral']
_DISCONNECTBTPERIPHERAL = DESCRIPTOR.message_types_by_name['DisconnectBTPeripheral']
_GETCONNECTEDBTPERIPHERAL = DESCRIPTOR.message_types_by_name['GetConnectedBTPeripheral']
_GETCONNECTEDBTPERIPHERALRESP = DESCRIPTOR.message_types_by_name['GetConnectedBTPeripheralResp']
ScanBTPeripheral = _reflection.GeneratedProtocolMessageType('ScanBTPeripheral', (_message.Message,), {
  'DESCRIPTOR' : _SCANBTPERIPHERAL,
  '__module__' : 'commands.bt_central_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.ScanBTPeripheral)
  })
_sym_db.RegisterMessage(ScanBTPeripheral)

ConnectToBTPeripheral = _reflection.GeneratedProtocolMessageType('ConnectToBTPeripheral', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTTOBTPERIPHERAL,
  '__module__' : 'commands.bt_central_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.ConnectToBTPeripheral)
  })
_sym_db.RegisterMessage(ConnectToBTPeripheral)

DisconnectBTPeripheral = _reflection.GeneratedProtocolMessageType('DisconnectBTPeripheral', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTBTPERIPHERAL,
  '__module__' : 'commands.bt_central_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.DisconnectBTPeripheral)
  })
_sym_db.RegisterMessage(DisconnectBTPeripheral)

GetConnectedBTPeripheral = _reflection.GeneratedProtocolMessageType('GetConnectedBTPeripheral', (_message.Message,), {
  'DESCRIPTOR' : _GETCONNECTEDBTPERIPHERAL,
  '__module__' : 'commands.bt_central_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetConnectedBTPeripheral)
  })
_sym_db.RegisterMessage(GetConnectedBTPeripheral)

GetConnectedBTPeripheralResp = _reflection.GeneratedProtocolMessageType('GetConnectedBTPeripheralResp', (_message.Message,), {
  'DESCRIPTOR' : _GETCONNECTEDBTPERIPHERALRESP,
  '__module__' : 'commands.bt_central_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetConnectedBTPeripheralResp)
  })
_sym_db.RegisterMessage(GetConnectedBTPeripheralResp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\242\002\005INSPB'
  _SCANBTPERIPHERAL._serialized_start=65
  _SCANBTPERIPHERAL._serialized_end=145
  _CONNECTTOBTPERIPHERAL._serialized_start=147
  _CONNECTTOBTPERIPHERAL._serialized_end=223
  _DISCONNECTBTPERIPHERAL._serialized_start=225
  _DISCONNECTBTPERIPHERAL._serialized_end=302
  _GETCONNECTEDBTPERIPHERAL._serialized_start=304
  _GETCONNECTEDBTPERIPHERAL._serialized_end=392
  _GETCONNECTEDBTPERIPHERALRESP._serialized_start=394
  _GETCONNECTEDBTPERIPHERALRESP._serialized_end=478
# @@protoc_insertion_point(module_scope)
