# coding: utf-8

"""
    EHESO API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from eheso_api_client.models.layer_inner import LayerInner  # noqa: E501

class TestLayerInner(unittest.TestCase):
    """LayerInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LayerInner:
        """Test LayerInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LayerInner`
        """
        model = LayerInner()  # noqa: E501
        if include_optional:
            return LayerInner(
                country_config = eheso_api_client.models.layer_inner_country_config.Layer_inner_countryConfig(
                    countries = [
                        null
                        ], ),
                access_config = [
                    null
                    ],
                id = '5f1b1b3b7f3b4b001f3b4b00',
                layer_id = 'HEI',
                name = 'Higher Education Institutions',
                description = '',
                collection_name = 'layer_hei',
                field_groups = [
                    null
                    ],
                fields = [
                    eheso_api_client.models.layer_inner_fields_inner.Layer_inner_fields_inner(
                        layer_id = 'HEI', 
                        is_key = 1, 
                        field_id = 'CY.YEAR', 
                        field_name = 'Reference year', 
                        field_type = 'number', )
                    ],
                extra_field_properties = [
                    null
                    ],
                countries = [
                    null
                    ]
            )
        else:
            return LayerInner(
        )
        """

    def testLayerInner(self):
        """Test LayerInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
