# coding: utf-8

"""
    EHESO API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from eheso_api_client.models.field_info_response_inner_info import FieldInfoResponseInnerInfo  # noqa: E501

class TestFieldInfoResponseInnerInfo(unittest.TestCase):
    """FieldInfoResponseInnerInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FieldInfoResponseInnerInfo:
        """Test FieldInfoResponseInnerInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FieldInfoResponseInnerInfo`
        """
        model = FieldInfoResponseInnerInfo()  # noqa: E501
        if include_optional:
            return FieldInfoResponseInnerInfo(
                category = '1. Auxiliary',
                sub_category = '1.1  ETER coverage',
                source = 'ETER',
                definition = '',
                indic_type = 'C'
            )
        else:
            return FieldInfoResponseInnerInfo(
        )
        """

    def testFieldInfoResponseInnerInfo(self):
        """Test FieldInfoResponseInnerInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
