class RoomEvents(str):
    RoomJoined = "room_joined"
    RoomJoinFailed = "room_join_failed"
    RoomClosed = "room_closed"
    RoomConnecting = "room_connecting"
    RoomWaiting = "room_waiting"
    NewPeerJoined = "new_peer_joined"
    LobbyPeerUpdated = "lobby_peer_updated"
    NewLobbyPeer = "new_lobby_peer"
    MetadataUpdated = "metadata_updated"
    RemotePeerLeft = "remote_peer_left"
    RoomControlsUpdated = "room_controls_updated"
    ActiveSpeakersChanged = "active_speakers_changed"
    RemotePeerRoleUpdated = "remote_peer_role_updated"
    RemoteProducerAdded = "remote_producer_added"
    RemoteProducerClosed = "remote_producer_closed"
