# generated by datamodel-codegen:
#   filename:  sphere.json
#   timestamp: 2024-12-02T15:48:32+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, PositiveFloat

from . import placement


class ISphere(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Radius: PositiveFloat = Field(..., description='The radius of the sphere')
    Angle1: float = Field(..., description='The angle of the sphere')
    Angle2: float = Field(..., description='The angle of the sphere')
    Angle3: float = Field(..., description='The angle of the sphere')
    Color: Optional[str] = Field('#808080', description='The color of the sphere')
    Placement: placement.Model
