# Generated by Django 5.1.1 on 2024-09-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalu', '0020_evaluationphase_evaluation_group_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationgroup',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Finished'),
        ),
        migrations.AddField(
            model_name='evaluationgroup',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finished at'),
        ),
    ]
