# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands/active_sensor_device.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.sensor_pb2 as sensor__pb2

from proto.sensor_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#commands/active_sensor_device.proto\x12\x11insta360.messages\x1a\x0csensor.proto\"\x17\n\x15GetActiveSensorDevice\"b\n\x19GetActiveSensorDeviceResp\x12/\n\x06\x64\x65vice\x18\x01 \x01(\x0e\x32\x1f.insta360.messages.SensorDevice\x12\x14\n\x0cmedia_offset\x18\x02 \x01(\t\"H\n\x15SetActiveSensorDevice\x12/\n\x06\x64\x65vice\x18\x01 \x01(\x0e\x32\x1f.insta360.messages.SensorDevice\"1\n\x19SetActiveSensorDeviceResp\x12\x14\n\x0cmedia_offset\x18\x01 \x01(\tB\x08\xa2\x02\x05INSPBP\x00\x62\x06proto3')



_GETACTIVESENSORDEVICE = DESCRIPTOR.message_types_by_name['GetActiveSensorDevice']
_GETACTIVESENSORDEVICERESP = DESCRIPTOR.message_types_by_name['GetActiveSensorDeviceResp']
_SETACTIVESENSORDEVICE = DESCRIPTOR.message_types_by_name['SetActiveSensorDevice']
_SETACTIVESENSORDEVICERESP = DESCRIPTOR.message_types_by_name['SetActiveSensorDeviceResp']
GetActiveSensorDevice = _reflection.GeneratedProtocolMessageType('GetActiveSensorDevice', (_message.Message,), {
  'DESCRIPTOR' : _GETACTIVESENSORDEVICE,
  '__module__' : 'commands.active_sensor_device_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetActiveSensorDevice)
  })
_sym_db.RegisterMessage(GetActiveSensorDevice)

GetActiveSensorDeviceResp = _reflection.GeneratedProtocolMessageType('GetActiveSensorDeviceResp', (_message.Message,), {
  'DESCRIPTOR' : _GETACTIVESENSORDEVICERESP,
  '__module__' : 'commands.active_sensor_device_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.GetActiveSensorDeviceResp)
  })
_sym_db.RegisterMessage(GetActiveSensorDeviceResp)

SetActiveSensorDevice = _reflection.GeneratedProtocolMessageType('SetActiveSensorDevice', (_message.Message,), {
  'DESCRIPTOR' : _SETACTIVESENSORDEVICE,
  '__module__' : 'commands.active_sensor_device_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.SetActiveSensorDevice)
  })
_sym_db.RegisterMessage(SetActiveSensorDevice)

SetActiveSensorDeviceResp = _reflection.GeneratedProtocolMessageType('SetActiveSensorDeviceResp', (_message.Message,), {
  'DESCRIPTOR' : _SETACTIVESENSORDEVICERESP,
  '__module__' : 'commands.active_sensor_device_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.SetActiveSensorDeviceResp)
  })
_sym_db.RegisterMessage(SetActiveSensorDeviceResp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\242\002\005INSPB'
  _GETACTIVESENSORDEVICE._serialized_start=72
  _GETACTIVESENSORDEVICE._serialized_end=95
  _GETACTIVESENSORDEVICERESP._serialized_start=97
  _GETACTIVESENSORDEVICERESP._serialized_end=195
  _SETACTIVESENSORDEVICE._serialized_start=197
  _SETACTIVESENSORDEVICE._serialized_end=269
  _SETACTIVESENSORDEVICERESP._serialized_start=271
  _SETACTIVESENSORDEVICERESP._serialized_end=320
# @@protoc_insertion_point(module_scope)
