# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands/start_looprecording.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"commands/start_looprecording.proto\x12\x11insta360.messages\"\x14\n\x12StartLoopRecording\"\x18\n\x16StartLoopRecordingRespB\x08\xa2\x02\x05INSPBb\x06proto3')



_STARTLOOPRECORDING = DESCRIPTOR.message_types_by_name['StartLoopRecording']
_STARTLOOPRECORDINGRESP = DESCRIPTOR.message_types_by_name['StartLoopRecordingResp']
StartLoopRecording = _reflection.GeneratedProtocolMessageType('StartLoopRecording', (_message.Message,), {
  'DESCRIPTOR' : _STARTLOOPRECORDING,
  '__module__' : 'commands.start_looprecording_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.StartLoopRecording)
  })
_sym_db.RegisterMessage(StartLoopRecording)

StartLoopRecordingResp = _reflection.GeneratedProtocolMessageType('StartLoopRecordingResp', (_message.Message,), {
  'DESCRIPTOR' : _STARTLOOPRECORDINGRESP,
  '__module__' : 'commands.start_looprecording_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.StartLoopRecordingResp)
  })
_sym_db.RegisterMessage(StartLoopRecordingResp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\242\002\005INSPB'
  _STARTLOOPRECORDING._serialized_start=57
  _STARTLOOPRECORDING._serialized_end=77
  _STARTLOOPRECORDINGRESP._serialized_start=79
  _STARTLOOPRECORDINGRESP._serialized_end=103
# @@protoc_insertion_point(module_scope)
