from Illuminate.Contracts.Foundation.Application import Application as Application
from Illuminate.Support.ServiceProvider import ServiceProvider

class DjingCoreServiceProvider(ServiceProvider):
    def __init__(self, app: Application) -> None: ...
    def register(self): ...
    def boot(self) -> None: ...
