#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2406-11-g9935d877"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2406
#define NETGEN_VERSION_TWEAK 11
#define NETGEN_VERSION_HASH "g9935d877"
#endif // NETGEN_VERSION_HPP_INCLUDED
