# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timelapse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftimelapse.proto\x12\x11insta360.messages\"\xcf\x01\n\x10TimelapseOptions\x12\x10\n\x08\x64uration\x18\x01 \x01(\r\x12\x11\n\tlapseTime\x18\x02 \x01(\r\x12\x43\n\x0boutput_type\x18\x03 \x01(\x0e\x32..insta360.messages.TimelapseOptions.OutputType\x12\x1b\n\x13\x61\x63\x63\x65lerate_fequency\x18\x04 \x01(\r\"4\n\nOutputType\x12\x0f\n\x0b\x44oNotChange\x10\x00\x12\t\n\x05Video\x10\x01\x12\n\n\x06Images\x10\x02*\xbd\x01\n\rTimelapseMode\x12\x13\n\x0fTIMELAPSE_MIXED\x10\x00\x12\x1a\n\x16MOBILE_TIMELAPSE_VIDEO\x10\x01\x12\x1f\n\x1bTIMELAPSE_INTERVAL_SHOOTING\x10\x02\x12\x1a\n\x16STATIC_TIMELAPSE_VIDEO\x10\x03\x12\x1c\n\x18TIMELAPSE_INTERVAL_VIDEO\x10\x04\x12 \n\x1cTIMELAPSE_STARLAPSE_SHOOTING\x10\x05\x42\x08\xa2\x02\x05INSPBb\x06proto3')

_TIMELAPSEMODE = DESCRIPTOR.enum_types_by_name['TimelapseMode']
TimelapseMode = enum_type_wrapper.EnumTypeWrapper(_TIMELAPSEMODE)
TIMELAPSE_MIXED = 0
MOBILE_TIMELAPSE_VIDEO = 1
TIMELAPSE_INTERVAL_SHOOTING = 2
STATIC_TIMELAPSE_VIDEO = 3
TIMELAPSE_INTERVAL_VIDEO = 4
TIMELAPSE_STARLAPSE_SHOOTING = 5


_TIMELAPSEOPTIONS = DESCRIPTOR.message_types_by_name['TimelapseOptions']
_TIMELAPSEOPTIONS_OUTPUTTYPE = _TIMELAPSEOPTIONS.enum_types_by_name['OutputType']
TimelapseOptions = _reflection.GeneratedProtocolMessageType('TimelapseOptions', (_message.Message,), {
  'DESCRIPTOR' : _TIMELAPSEOPTIONS,
  '__module__' : 'timelapse_pb2'
  # @@protoc_insertion_point(class_scope:insta360.messages.TimelapseOptions)
  })
_sym_db.RegisterMessage(TimelapseOptions)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\242\002\005INSPB'
  _TIMELAPSEMODE._serialized_start=249
  _TIMELAPSEMODE._serialized_end=438
  _TIMELAPSEOPTIONS._serialized_start=39
  _TIMELAPSEOPTIONS._serialized_end=246
  _TIMELAPSEOPTIONS_OUTPUTTYPE._serialized_start=194
  _TIMELAPSEOPTIONS_OUTPUTTYPE._serialized_end=246
# @@protoc_insertion_point(module_scope)
