
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-29T13:34:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b173bb82ff75f8a986f7bcdea4486e503004a0bc",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
