DATE_FORMAT = "%Y-%m-%d"
DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S.%f%z"

MONTHS_HAVING_LESS_THAN_30_DAYS = set([2])
MONTHS_HAVING_30_DAYS = set([4, 6, 9, 11])
MONTHS_HAVING_31_DAYS = set([1, 3, 5, 7, 8, 10, 12])
NUM_MONTHS_PER_YEAR = 12
NUM_DAYS_PER_WEEK = 7

