from Illuminate.Contracts.Support.JsonSerializable import JsonSerializable
from djing.core.AuthorizedToSee import AuthorizedToSee
from djing.core.Makeable import Makeable

class Breadcrumbs(AuthorizedToSee, Makeable, JsonSerializable):
    def __init__(self, items=[]) -> None: ...
    def items(self, items) -> None: ...
    def json_serialize(self) -> list: ...
