# coding: utf-8

"""
    EHESO API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class FieldDataResponseFormatSchema(str, Enum):
    """
    The response format for the field data
    """

    """
    allowed enum values
    """
    DEFAULT = 'default'
    FLAT = 'flat'
    SQL = 'sql'

    @classmethod
    def from_json(cls, json_str: str) -> FieldDataResponseFormatSchema:
        """Create an instance of FieldDataResponseFormatSchema from a JSON string"""
        return FieldDataResponseFormatSchema(json.loads(json_str))


