from djing.core.Metrics.Metric import Metric
from typing import Self

class RangedMetric(Metric):
    def ranges(self) -> dict: ...
    def default_range(self, key) -> Self: ...
    def json_serialize(self): ...
