# coding: utf-8

"""
    EHESO API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from eheso_api_client.models.layer_layer_id_query_test_post_request import LayerLayerIdQueryTestPostRequest  # noqa: E501

class TestLayerLayerIdQueryTestPostRequest(unittest.TestCase):
    """LayerLayerIdQueryTestPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LayerLayerIdQueryTestPostRequest:
        """Test LayerLayerIdQueryTestPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LayerLayerIdQueryTestPostRequest`
        """
        model = LayerLayerIdQueryTestPostRequest()  # noqa: E501
        if include_optional:
            return LayerLayerIdQueryTestPostRequest(
                format = 'default',
                result_info = True,
                limit = 56,
                locale = '',
                find = {
                    'key' : None
                    },
                select = [
                    ''
                    ],
                deselect = [
                    ''
                    ],
                sort = {
                    'key' : '-1'
                    },
                config = eheso_api_client.models.data_access_config_schema.DataAccessConfigSchema(
                    restricted_documents = { }, 
                    restricted_fields = [
                        ''
                        ], 
                    grants = {
                        'key' : eheso_api_client.models.data_access_config_schema_grants_value.DataAccessConfigSchema_grants_value(
                            documents = { }, 
                            fields = [
                                ''
                                ], )
                        }, )
            )
        else:
            return LayerLayerIdQueryTestPostRequest(
        )
        """

    def testLayerLayerIdQueryTestPostRequest(self):
        """Test LayerLayerIdQueryTestPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
