# coding: utf-8

"""
    Livoltek API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pylivoltek
from pylivoltek.models.inline_response2008_data import InlineResponse2008Data  # noqa: E501
from pylivoltek.rest import ApiException


class TestInlineResponse2008Data(unittest.TestCase):
    """InlineResponse2008Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2008Data(self):
        """Test InlineResponse2008Data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pylivoltek.models.inline_response2008_data.InlineResponse2008Data()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
