##### Edamam API EXCLUSIVE #####
INCLUDED_FIELDS = (
    "uri",
    "label",
    "image",
    "images",
    "source",
    "url",
    "shareAs",
    "yield",
    "dietLabels",
    "healthLabels",
    "cautions",
    "ingredientLines",
    "ingredients",
    "calories",
    "glycemicIndex",
    "inflammatoryIndex",
    "totalCO2Emissions",
    "totalWeight",
    "totalTime",
    "cuisineType",
    "mealType",
    "dishType",
    "totalNutrients",
    "totalDaily",
    "digest",
    "tags",
    "externalId",
)
RANDOM_FIELD = ("true", "false")
IMAGE_SIZE = ("LARGE", "REGULAR", "SMALL", "THUMBNAIL")
DISH_TYPE = (
    "Biscuits and cookies",
    "Bread",
    "Cereals",
    "Condiments and sauces",
    "Desserts",
    "Drinks",
    "Main course",
    "Pancake",
    "Preps",
    "Preserve",
    "Salad",
    "Sandwiches",
    "Side dish",
    "Soup",
    "Starter",
    "Sweets",
)
MEAL_TYPE = ("Breakfast", "Dinner", "Lunch", "Snack", "Teatime")
HEALTH_TYPE = (
    "alcohol-cocktail",
    "alcohol-free",
    "celery-free",
    "crustacean-free",
    "dairy-free",
    "DASH",
    "egg-free",
    "fish-free",
    "fodmap-free",
    "gluten-free",
    "immuno-supportive",
    "keto-friendly",
    "kidney-friendly",
    "kosher",
    "low-fat-abs",
    "low-potassium",
    "low-sugar",
    "lupine-free",
    "Mediterranean",
    "mollusk-free",
    "mustard-free",
    "no-oil-added",
    "paleo",
    "peanut-free",
    "pescatarian",
    "pork-free",
    "red-meat-free",
    "sesame-free",
    "shellfish-free",
    "soy-free",
    "sugar-conscious",
    "sulfite-free",
    "tree-nut-free",
    "vegan",
    "vegetarian",
    "wheat-free",
)
CUISINE_TYPE = (
    "American",
    "Asian",
    "British",
    "Caribbean",
    "Central Europe",
    "Chinese",
    "Eastern Europe",
    "French",
    "Indian",
    "Italian",
    "Japanese",
    "Kosher",
    "Mediterranean",
    "Mexican",
    "Middle Eastern",
    "Nordic",
    "South American",
    "South East Asian",
)
DIET_TYPE = (
    "balanced",
    "high-fiber",
    "high-protein",
    "low-carb",
    "low-fat",
    "low-sodium",
)

##### Allergies ######
# maps different allergies to the health_type
ALLERGIES_MAPPING = {
    "celery": "celery-free",
    "gluten": "gluten-free",
    "crustaceans": "crustacean-free",
    "eggs": "egg-free",
    "fish": "fish-free",
    "lupins": "lupine-free",
    "dairy": "dairy-free",
    "molluscs": "mollusk-free",
    "mustard": "mustard-free",
    "nuts": "tree-nut-free",
    "peanuts": "peanut-free",
    "sesame": "sesame-free",
    "soy": "soy-free",
    "sulfites": "sulfite-free",
    "shellfish": "shellfish-free",
    "fodmap": "fodmap-free",
}
