from djing.core.AuthorizedToSee import AuthorizedToSee
from djing.core.Element import Element
from djing.core.HasMenu import HasMenu
from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest
from djing.core.Makeable import Makeable

class Dashboard(Element, AuthorizedToSee, Makeable, HasMenu):
    def name(self): ...
    def label(self): ...
    def uri_key(self): ...
    def menu(self, request: DjingRequest): ...
    def show_refresh_button(self): ...
