from Illuminate.Routing.Router import Router as Router
from typing import Self

class PendingRouteRegistration:
    def __init__(self) -> None: ...
    def with_authentication_routes(self) -> Self: ...
    def register(self) -> None: ...
