from _typeshed import Incomplete
from django.db.models import Model as Model
from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest

class Util:
    @classmethod
    def username_field(cls): ...
    @classmethod
    def auth_user_model(cls): ...
    @classmethod
    def is_djing_request(cls, request: DjingRequest): ...
    @classmethod
    def is_djing_api_request(cls, request: DjingRequest): ...
    @classmethod
    def is_dev_mode(cls) -> bool: ...
    @classmethod
    def get_user_from_request(cls, request: DjingRequest): ...
    @classmethod
    def get_key_name(cls, resource: Model): ...
    @classmethod
    def model_to_dict(cls, instance, fields: Incomplete | None = None, exclude: Incomplete | None = None): ...
