from djing.core.Actions.Action import Action as Action
from djing.core.Http.Requests.DjingRequest import DjingRequest
from djing.core.Http.Requests.QueriesResources import QueriesResources
from djing.core.Resource import Resource as Resource

class ActionRequest(QueriesResources, DjingRequest):
    request_name: str
    current_action: Action | None
    def action(self) -> Action: ...
    def validate_fields(self): ...
    def resolve_fields(self, request: DjingRequest): ...
    def resolve_actions(self): ...
    def available_actions(self): ...
    def action_exists(self) -> bool: ...
    def chunks(self, count, callback): ...
    def to_selected_resource_query(self): ...
